version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/lib/migasfree/${FQDN}/frontend/certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/var/lib/migasfree/${FQDN}/frontend/vhost.d:/etc/nginx/vhost.d"
      - "/var/lib/migasfree/${FQDN}/frontend/conf.d:/etc/nginx/conf.d"
      - "/var/lib/migasfree/${FQDN}/frontend/html:/usr/share/nginx/html"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"
    networks:
      - frontend
  
  letsencrypt:
    hostname: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    depends_on: 
      - nginx-proxy
    volumes:
      - "/var/lib/migasfree/${FQDN}/frontend/certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/migasfree/${FQDN}/frontend/vhost.d:/etc/nginx/vhost.d"
      - "/var/lib/migasfree/${FQDN}frontend/conf.d:/etc/nginx/conf.d"
      - "/var/lib/migasfree/${FQDN}/frontend/html:/usr/share/nginx/html"
    networks:
      - frontend

  server:
    hostname: server
    image: vitalinux/migasfreeserver:${MIGASFREE_VERSION}
    container_name: ${FQDN}-server
    environment:
      LETSENCRYPT_HOST: migasfree.educa.aragon.com
      LETSENCRYPT_EMAIL: vitalinux@educa.aragon.es
      HTTPS_METHOD: noredirect
      VIRTUAL_HOST: migasfree.educa.aragon.com
      FQDN: ${FQDN}
      TZ: ${TZ}
      POSTGRES_PORT: ${POSTGRES_PORT}
    restart: always
    depends_on:
      - db
    volumes:
      - "/var/lib/migasfree/${FQDN}/conf:/etc/migasfree-server"
      - "/var/lib/migasfree/${FQDN}/public:/var/migasfree/repo"
      - "/var/lib/migasfree/${FQDN}/keys:/usr/share/migasfree-server"
      - "/var/lib/migasfree/${FQDN}/sites-available:/etc/nginx/sites-available"
      - "/var/www:/var/www"
    networks:
      - frontend
      - backend
  db:
    hostname: db
    image: vitalinux/migasfreedb:${MIGASFREE_VERSION_DB}
    container_name: ${FQDN}-db
    environment:
      POSTGRES_CRON: ${POSTGRES_CRON}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ALLOW_HOSTS: ${POSTGRES_ALLOW_HOSTS}
      TZ: ${TZ}
    restart: always
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
      - "/var/lib/migasfree/${FQDN}/conf:/etc/migasfree-server"
      - "/var/lib/migasfree/${FQDN}/data:/var/lib/postgresql/data"
      - "/var/lib/migasfree/${FQDN}/dump:/var/migasfree/dump"
    networks:
      - backend  

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge